-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 23:36:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema goilc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ci_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_sessions` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ci_sessions_timestamp` (`timestamp` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NULL DEFAULT NULL,
  `user_password` VARCHAR(45) NULL DEFAULT NULL,
  `user_full_name` VARCHAR(255) NULL DEFAULT NULL,
  `user_image` VARCHAR(255) NULL DEFAULT NULL,
  `user_description` TEXT NULL DEFAULT NULL,
  `user_role_role_id` INT(11) NULL,
  `user_input_date` TIMESTAMP NULL DEFAULT NULL,
  `user_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_last_login` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_role1_idx` (`user_role_role_id` ASC),
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_role_id`)
    REFERENCES `user_roles` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(100) NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trainings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainings` (
  `training_id` INT NOT NULL AUTO_INCREMENT,
  `training_name` VARCHAR(255) NULL,
  `training_place` VARCHAR(255) NULL,
  `training_date_start` DATE NULL,
  `training_date_end` DATE NULL,
  `training_time` TIME NULL,
  `training_price` DECIMAL NULL,
  `training_brocure` VARCHAR(255) NULL,
  `training_cover_letter` TEXT NULL,
  `training_silabus` VARCHAR(100) NULL,
  `training_status` TINYINT(1) NULL DEFAULT 1,
  `category_id` INT NULL,
  `service_id` INT NULL,
  `user_id` INT(11) NULL,
  `training_input_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `training_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`training_id`),
  INDEX `fk_trainings_users1_idx` (`user_id` ASC),
  INDEX `fk_trainings_categories1_idx` (`category_id` ASC),
  INDEX `fk_trainings_services1_idx` (`service_id` ASC),
  CONSTRAINT `fk_trainings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_trainings_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `categories` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_trainings_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `services` (`service_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(100) NULL,
  `client_image` VARCHAR(255) NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mailbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mailbox` (
  `mailbox_id` INT NOT NULL AUTO_INCREMENT,
  `mailbox_name` VARCHAR(255) NULL,
  `mailbox_email` VARCHAR(100) NULL,
  `mailbox_phone` VARCHAR(15) NULL,
  `mailbox_corporate` VARCHAR(100) NULL,
  `mailbox_subject` VARCHAR(255) NULL,
  `mailbox_desc` TEXT NULL,
  `mailbox_status` TINYINT(1) NULL DEFAULT 0,
  `mailbox_input_date` TIMESTAMP NULL,
  `mailbox_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`mailbox_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news` (
  `news_id` INT NOT NULL,
  `news_title` VARCHAR(100) NULL,
  `news_desc` TEXT NULL,
  `news_image` VARCHAR(255) NULL,
  `news_type` ENUM('Corporate', 'Internal', 'Eksternal') NULL,
  `user_id` INT(11) NULL,
  `news_input_date` TIMESTAMP NULL,
  `news_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`news_id`),
  INDEX `fk_news_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_news_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gallery` (
  `gallery_id` INT NOT NULL AUTO_INCREMENT,
  `gallery_name` VARCHAR(100) NULL,
  `gallery_place` VARCHAR(100) NULL,
  `gallery_image` VARCHAR(255) NULL,
  `gallery_desc` TEXT NULL,
  `gallery_date` DATE NULL,
  PRIMARY KEY (`gallery_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registers` (
  `register_id` INT NOT NULL AUTO_INCREMENT,
  `register_no` VARCHAR(45) NULL,
  `register_corporate` VARCHAR(100) NULL,
  `register_pic_name` VARCHAR(255) NULL,
  `register_pic_jab` VARCHAR(100) NULL,
  `register_pic_tlp` VARCHAR(15) NULL,
  `register_pic_fax` VARCHAR(15) NULL,
  `register_pic_phone` VARCHAR(15) NULL,
  `register_pic_email` VARCHAR(100) NULL,
  `register_pay_name` VARCHAR(255) NULL,
  `register_pay_jab` VARCHAR(255) NULL,
  `register_pay_tlp` VARCHAR(15) NULL,
  `register_pay_fax` VARCHAR(15) NULL,
  `register_pay_phone` VARCHAR(15) NULL,
  `register_add_inv` TEXT NOT NULL,
  `training_id` INT NULL,
  `register_status` TINYINT NULL DEFAULT 0 COMMENT '0 = proses\n1 = setuju\n2 = tolak',
  `register_input_date` TIMESTAMP NULL,
  `register_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`register_id`),
  INDEX `fk_registers_trainings1_idx` (`training_id` ASC),
  CONSTRAINT `fk_registers_trainings1`
    FOREIGN KEY (`training_id`)
    REFERENCES `trainings` (`training_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `member_name` VARCHAR(255) NULL,
  `member_jab` VARCHAR(100) NULL,
  `member_phone` VARCHAR(15) NULL,
  `member_email` VARCHAR(100) NULL,
  `register_id` INT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_members_registers1_idx` (`register_id` ASC),
  CONSTRAINT `fk_members_registers1`
    FOREIGN KEY (`register_id`)
    REFERENCES `registers` (`register_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subscribers` (
  `subscriber_id` INT NOT NULL AUTO_INCREMENT,
  `subscriber_email` VARCHAR(100) NULL,
  `subscriber_input_date` TIMESTAMP NULL,
  `subscriber_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`subscriber_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blastings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blastings` (
  `blasting_id` INT NOT NULL AUTO_INCREMENT,
  `blasting_title` VARCHAR(255) NULL,
  `blasting_letter` TEXT NULL,
  `blasting_status` TINYINT(1) NULL DEFAULT 0,
  `user_id` INT(11) NULL,
  `blasting_input_date` TIMESTAMP NULL,
  `blasting_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`blasting_id`),
  INDEX `fk_blastings_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_blastings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recruitments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recruitments` (
  `recruitment_id` INT NOT NULL AUTO_INCREMENT,
  `recruitment_title` VARCHAR(100) NULL,
  `recruitment_letter` TEXT NULL,
  `recruitment_status` TINYINT(1) NULL DEFAULT 0,
  `user_id` INT(11) NULL,
  `recruitment_input_date` TIMESTAMP NULL,
  `recruitment_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`recruitment_id`),
  INDEX `fk_recruitments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_recruitments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `settings` (
  `setting_id` INT NOT NULL AUTO_INCREMENT,
  `setting_name` TEXT NULL,
  `setting_value` TEXT NULL,
  `setting_last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slideshows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slideshows` (
  `slideshow_id` INT NOT NULL AUTO_INCREMENT,
  `slideshow_name` VARCHAR(100) NULL,
  `slideshow_image` VARCHAR(255) NULL,
  `slideshow_status` TINYINT(1) NULL DEFAULT 0,
  `user_id` INT(11) NULL,
  `slideshow_input_date` TIMESTAMP NULL,
  `slideshow_last_update` TIMESTAMP NULL,
  PRIMARY KEY (`slideshow_id`),
  INDEX `fk_slideshows_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_slideshows_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
